Case1/force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Case1/force-app/main/default/objects/Card__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Case1/force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Case1/force-app/main/default/objects/Cart__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Case1/force-app/main/default/objects/Cart__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Case1/force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Case1/force-app/main/default/objects/User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Case1/force-app/main/default/classes/UserController.cls
public with sharing class UserController {
	@AuraEnabled
    public static User__c getUser(User__c user){
        system.debug(user.Email__c);
        system.debug(user.Password__c);
        String email = user.Email__c;
        User__c getUser = NULL;
        try{
            getUser = [SELECT Name,
                       Email__c, 
                       Password__c, 
                       (SELECT Name, Amount__c FROM Cards__r), 
                       (SELECT Product__r.Name, Quantity__c FROM Carts__r)
                       FROM User__c
                       WHERE Email__c = :email];
        }catch(Exception e){
            
        }
        if (getUser != NULL) {
            if(getUser.Password__c == user.Password__c){
                system.debug('true');
                getUser.Password__c = '';
                system.debug(getUser);
                return getUser;
            } else {
            	system.debug('false');
            	return user;
            }
        }else {
            system.debug('false');
            return user;
        }
        
    }
    
    @AuraEnabled
    public static User__c newUser(User__c user){
        if (!getUser(user).Password__c.equals('')){
            insert user;
            return getUser(user);
        }else{
            return user;
        }
    }
}