Case1/force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Case1/force-app/main/default/objects/Product_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Case1/force-app/main/default/classes/ShopController.cls
public with sharing class ShopController {
    @AuraEnabled
    public static List<sObject> getProducts() {
        
        return [SELECT Name, Price__c, (SELECT Name FROM Product_Categories__r) 
                FROM Product__c];
    }
    
    @AuraEnabled
    public static List<sObject> getCategories() {
        return [SELECT Name FROM Product_Category__c GROUP BY Name];
    }
    
    @AuraEnabled
    public static List<sObject> getProduct(List<String> filters) {
        
        return [SELECT Name, Price__c, (SELECT Name FROM Product_Categories__r)
                FROM Product__c
				WHERE Id in (SELECT Product__c 
                             FROM Product_Category__c 
                             WHERE Name in :filters)];
    }
}